### ISSUE TITLE
language selection dropdown  is not there

### ISSUE THREAD

**Issue by hsmandavi111** [AI4Bharat/Indic-Typing-UI#3]
unable to select language

**Comment by GokulNC** [comment]
Thanks a lot for reporting! It has been fixed now, please check.

**Comment by RYG81** [comment]
I still don't see that. Anything to do other than those two command mentioned in README

**Comment by GokulNC** [comment]
It still shows the dropdown here for me: https://xlit.ai4bharat.org/

**Comment by RYG81** [comment]
But i clone repo and followed readme instructions, i did not get that option to choose language.

**Comment by RYG81** [comment]
![image](https://user-images.githubusercontent.com/10570236/232201414-d7f4905e-b464-470e-a9ff-fdfa07b34cdb.png)
This is what I have.

![image](https://user-images.githubusercontent.com/10570236/232201635-2e7793bc-504a-4777-962d-881ec9bed54d.png)
Getting error

**Comment by RYG81** [comment]
And for converter also no language--
![image](https://user-images.githubusercontent.com/10570236/232201743-140942aa-bf34-4f62-8af0-c9c316676ec0.png)

**Comment by RYG81** [comment]
any way resolve this?

**Comment by GokulNC** [comment]
Can you open your console logs to see if there are any errors?

**Comment by RYG81** [comment]
Sure, will check and let you know tomorrow.

**Comment by RYG81** [comment]
![image](https://user-images.githubusercontent.com/10570236/232278997-204cb6fb-2d1b-451c-a1b4-d3f1381c074b.png)
Here is the terminal screen

![image](https://user-images.githubusercontent.com/10570236/232279056-98ba9ac4-213f-4c5b-bfc5-d50667affcbb.png)
Here is the web console.

**Comment by RYG81** [comment]
any way to solve this.

**Comment by azrael05** [comment]
Facing the same issue. Were you able to resolve that?

**Comment by RYG81** [comment]
no unfortunately not yet.

**Comment by GokulNC** [comment]
You will have to [run the backend API server yourself as shown here](https://pypi.org/project/ai4bharat-transliteration/#:~:text=ur%27%3A%20%27%D9%86%D9%85%D8%B3%DA%A9%D8%A7%D8%B1%20%D8%A8%DA%BE%D8%A7%D8%B1%D8%AA%27%7D-,Web%20API%20Server,-Running%20a%20flask) and use that URL here:
https://github.com/AI4Bharat/Indic-Input-Tool-UI/blob/859be753f1b032e36692dc4e05990a93364786dc/js/api.js#L1

**Comment by RYG81** [comment]
Ok, i checked that before but what need to be downloaded to run that server. I tried pip code given at top of backend page with no success
